from enum import Enum
from typing import List
from dataclasses import dataclass, field
from datetime import datetime

from app.domain.actions import ActionType
from app.intelligence.scoring import RecoverabilityLevel
from app.intelligence.recovery_signals import UrgencyLevel


class ActionabilityState(str, Enum):
    READY = "READY"
    WAIT = "WAIT"
    DO_NOT_ACT = "DO_NOT_ACT"


@dataclass(frozen=True)
class RecoveryOpportunity:
    """Structured representation of a recovery opportunity generated by the intelligence layer.
    
    This domain model is ADVISORY ONLY. It supplies contextual intelligence to the AI Agent
    and CANNOT directly authorize execution or bypass the DeterministicPolicyEngine.
    """
    opportunity_id: str
    case_id: str
    payment_id: str
    recoverability_level: RecoverabilityLevel
    recoverability_score: float  # Deterministic heuristic indicator (0.0 to 100.0)
    primary_reason: str
    supporting_signals: List[str] = field(default_factory=list)
    risk_factors: List[str] = field(default_factory=list)
    urgency: UrgencyLevel = UrgencyLevel.MEDIUM
    actionability: ActionabilityState = ActionabilityState.READY
    candidate_action_types: List[ActionType] = field(default_factory=list)
    detected_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self) -> None:
        if not (0.0 <= self.recoverability_score <= 100.0):
            raise ValueError(f"recoverability_score {self.recoverability_score} must be between 0.0 and 100.0.")
        if not self.opportunity_id.strip():
            raise ValueError("opportunity_id cannot be empty.")
        if not self.case_id.strip():
            raise ValueError("case_id cannot be empty.")
        if not self.payment_id.strip():
            raise ValueError("payment_id cannot be empty.")
