from enum import Enum
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime
import uuid


class AuditEventType(str, Enum):
    CASE_DETECTED = "CASE_DETECTED"
    OPPORTUNITY_DETECTED = "OPPORTUNITY_DETECTED"
    AGENT_ANALYSIS_STARTED = "AGENT_ANALYSIS_STARTED"
    AGENT_DECISION_CREATED = "AGENT_DECISION_CREATED"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_REJECTED = "ACTION_REJECTED"
    EXECUTION_DISPATCHED = "EXECUTION_DISPATCHED"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    OUTCOME_RECORDED = "OUTCOME_RECORDED"
    RECOVERY_EXECUTED = "RECOVERY_EXECUTED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    RECOVERY_SUCCEEDED = "RECOVERY_SUCCEEDED"
    CASE_EVALUATED = "CASE_EVALUATED"
    CASE_ESCALATED = "CASE_ESCALATED"
    CASE_STOPPED = "CASE_STOPPED"
    
    # Phase 1G Extended Operational Audit Events
    JOB_CREATED = "JOB_CREATED"
    JOB_STARTED = "JOB_STARTED"
    JOB_RETRY_SCHEDULED = "JOB_RETRY_SCHEDULED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    JOB_DEAD_LETTERED = "JOB_DEAD_LETTERED"
    EXECUTION_PROCESSING = "EXECUTION_PROCESSING"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_RECONCILED = "EXECUTION_RECONCILED"
    WEBHOOK_DUPLICATE = "WEBHOOK_DUPLICATE"
    EXECUTION_DUPLICATE = "EXECUTION_DUPLICATE"

    # Phase 1H Operational & Reliability Audit Events
    JOB_RETRY_REQUESTED = "JOB_RETRY_REQUESTED"
    JOB_CANCELLED = "JOB_CANCELLED"
    JOB_REQUEUED = "JOB_REQUEUED"
    RECOVERY_PAUSED = "RECOVERY_PAUSED"
    RECOVERY_RESUMED = "RECOVERY_RESUMED"
    RECOVERY_STOPPED = "RECOVERY_STOPPED"
    CIRCUIT_BREAKER_OPENED = "CIRCUIT_BREAKER_OPENED"
    CIRCUIT_BREAKER_HALF_OPENED = "CIRCUIT_BREAKER_HALF_OPENED"
    CIRCUIT_BREAKER_CLOSED = "CIRCUIT_BREAKER_CLOSED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"

    # Phase 1I Security Audit Events
    AUTHENTICATION_SUCCEEDED = "AUTHENTICATION_SUCCEEDED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    REPLAY_REJECTED = "REPLAY_REJECTED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    SECURITY_CONFIGURATION_ERROR = "SECURITY_CONFIGURATION_ERROR"
    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    EXPIRED_WEBHOOK = "EXPIRED_WEBHOOK"
    CORRELATION_ID_ASSIGNED = "CORRELATION_ID_ASSIGNED"

    # Phase 1J Job Infrastructure & Worker Audit Events
    JOB_CLAIMED = "JOB_CLAIMED"
    JOB_SUCCEEDED = "JOB_SUCCEEDED"
    JOB_LEASE_EXPIRED = "JOB_LEASE_EXPIRED"
    PROVIDER_CIRCUIT_BLOCKED = "PROVIDER_CIRCUIT_BLOCKED"
    WORKER_STARTED = "WORKER_STARTED"
    WORKER_STOPPING = "WORKER_STOPPING"
    WORKER_STOPPED = "WORKER_STOPPED"
    WORKER_CRASH_RECOVERY = "WORKER_CRASH_RECOVERY"
    JOB_PAUSED = "JOB_PAUSED"

    # Phase 1K Distributed Worker & Domain Event Audit Events
    WORKER_REGISTERED = "WORKER_REGISTERED"
    WORKER_HEARTBEAT = "WORKER_HEARTBEAT"
    WORKER_DRAINING = "WORKER_DRAINING"
    WORKER_LOST = "WORKER_LOST"
    WORKER_FAILOVER_STARTED = "WORKER_FAILOVER_STARTED"
    WORKER_FAILOVER_COMPLETED = "WORKER_FAILOVER_COMPLETED"
    JOB_DEDUPLICATED = "JOB_DEDUPLICATED"
    BACKPRESSURE_LEVEL_CHANGED = "BACKPRESSURE_LEVEL_CHANGED"
    EVENT_PUBLISHED = "EVENT_PUBLISHED"
    EVENT_CONSUMED = "EVENT_CONSUMED"
    EVENT_DUPLICATE_SUPPRESSED = "EVENT_DUPLICATE_SUPPRESSED"

    # Phase 2B Provider Lifecycle & Operation Audit Events
    PROVIDER_REGISTERED = "PROVIDER_REGISTERED"
    PROVIDER_ENABLED = "PROVIDER_ENABLED"
    PROVIDER_DISABLED = "PROVIDER_DISABLED"
    PROVIDER_CONFIGURATION_VALIDATED = "PROVIDER_CONFIGURATION_VALIDATED"
    PROVIDER_CONFIGURATION_FAILED = "PROVIDER_CONFIGURATION_FAILED"
    PROVIDER_EXECUTION_REQUESTED = "PROVIDER_EXECUTION_REQUESTED"
    PROVIDER_EXECUTION_ACCEPTED = "PROVIDER_EXECUTION_ACCEPTED"
    PROVIDER_EXECUTION_COMPLETED = "PROVIDER_EXECUTION_COMPLETED"
    PROVIDER_EXECUTION_FAILED = "PROVIDER_EXECUTION_FAILED"
    PROVIDER_EXECUTION_TIMEOUT = "PROVIDER_EXECUTION_TIMEOUT"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_WEBHOOK_RECEIVED = "PROVIDER_WEBHOOK_RECEIVED"
    PROVIDER_WEBHOOK_REJECTED = "PROVIDER_WEBHOOK_REJECTED"
    PROVIDER_WEBHOOK_DUPLICATE = "PROVIDER_WEBHOOK_DUPLICATE"
    PROVIDER_CAPABILITY_REJECTED = "PROVIDER_CAPABILITY_REJECTED"
    PROVIDER_LIFECYCLE_CHANGED = "PROVIDER_LIFECYCLE_CHANGED"



@dataclass(frozen=True)
class AuditEvent:
    """Immutable audit trail log record."""
    event_id: str
    case_id: str
    event_type: AuditEventType
    actor: str
    timestamp: datetime = field(default_factory=datetime.now)
    details: Dict[str, Any] = field(default_factory=dict)
    correlation_id: Optional[str] = None


class AuditTrail:
    """Append-only audit trail logger enforcing complete traceability."""

    def __init__(self) -> None:
        self._events: List[AuditEvent] = []

    def record(
        self,
        case_id: str,
        event_type: AuditEventType,
        actor: str,
        details: Dict[str, Any] = None,
        correlation_id: Optional[str] = None,
    ) -> AuditEvent:
        event = AuditEvent(
            event_id=f"evt_{uuid.uuid4().hex[:12]}",
            case_id=case_id,
            event_type=event_type,
            actor=actor,
            timestamp=datetime.now(),
            details=details or {},
            correlation_id=correlation_id,
        )
        self._events.append(event)
        return event

    def get_events_for_case(self, case_id: str) -> List[AuditEvent]:
        return [e for e in self._events if e.case_id == case_id]

    @property
    def all_events(self) -> List[AuditEvent]:
        return list(self._events)
