from typing import Dict, Any, Optional
from decimal import Decimal
from datetime import datetime
import uuid

from app.domain.payment import Payment, FailureCode
from app.domain.actions import ActionType
from app.domain.execution import RecoveryExecution, ExecutionStatus
from app.domain.outcome import RecoveryOutcome, OutcomeStatus
from app.domain.orchestrator import PolicyApprovalRequiredError
from app.domain.decision import AgentDecision
from app.domain.policy import PolicyDecision

from app.simulation.scenarios import SimulationScenario, SimulationConfig


class SimulatedRecoveryExecutor:
    """Strongly-typed, zero-randomness simulated recovery execution engine.
    
    Responsibilities:
    - Accepts ONLY authorized RecoveryExecution contracts (rejects direct AgentDecision, Opportunity, PolicyDecision).
    - Enforces idempotency via an in-memory execution registry.
    - Generates deterministic RecoveryOutcome results based on payment failure code, action type, attempt count, and scenario configuration.
    - Has ZERO policy authority and ZERO AI decision capability.
    """

    def __init__(self, default_config: Optional[SimulationConfig] = None) -> None:
        self.default_config = default_config or SimulationConfig(scenario=SimulationScenario.CONTEXT_AWARE)
        self._execution_registry: Dict[str, RecoveryOutcome] = {}

    def execute(
        self,
        execution: Any,
        payment: Payment,
        config_or_scenario: Optional[SimulationScenario | SimulationConfig] = None,
    ) -> RecoveryOutcome:
        """Executes a policy-approved RecoveryExecution contract deterministically.
        
        Args:
            execution: Authorized RecoveryExecution instance dispatched by RecoveryOrchestrator.
            payment: Payment domain model context.
            config_or_scenario: Optional scenario override for explicit testing.
            
        Returns:
            RecoveryOutcome: Deterministic outcome of the execution.
            
        Raises:
            PolicyApprovalRequiredError: If execution is not a valid RecoveryExecution instance.
        """
        # 1. Authorization & Input validation
        if isinstance(execution, (AgentDecision, PolicyDecision)):
            raise PolicyApprovalRequiredError(
                f"SimulatedRecoveryExecutor rejected input of type '{type(execution).__name__}'. "
                "Only authorized RecoveryExecution contracts generated by RecoveryOrchestrator can be executed."
            )
            
        if hasattr(execution, "opportunity_id") or type(execution).__name__ == "RecoveryOpportunity":
            raise PolicyApprovalRequiredError(
                "SimulatedRecoveryExecutor rejected RecoveryOpportunity. "
                "Opportunities are advisory only and cannot be executed directly."
            )

        if not isinstance(execution, RecoveryExecution):
            raise PolicyApprovalRequiredError(
                f"Invalid execution contract: expected RecoveryExecution, got '{type(execution).__name__}'."
            )

        # 2. Idempotency Check
        idempotency_key = execution.idempotency_key
        if idempotency_key in self._execution_registry:
            # Return original stored outcome without creating a second simulated recovery event
            return self._execution_registry[idempotency_key]

        # 3. Determine Scenario Config
        config: SimulationConfig
        if config_or_scenario is None:
            config = self.default_config
        elif isinstance(config_or_scenario, SimulationScenario):
            config = SimulationConfig(scenario=config_or_scenario)
        elif isinstance(config_or_scenario, SimulationConfig):
            config = config_or_scenario
        else:
            config = self.default_config

        # 4. Resolve Outcome Deterministically
        status: OutcomeStatus
        recovered_amount: Decimal = Decimal("0.00")
        failure_reason: Optional[str] = None

        if config.scenario == SimulationScenario.SUCCESS:
            status = OutcomeStatus.RECOVERED
            recovered_amount = payment.amount
        elif config.scenario == SimulationScenario.FAILURE:
            status = OutcomeStatus.NOT_RECOVERED
            recovered_amount = Decimal("0.00")
            failure_reason = config.force_failure_reason or "Simulated execution failed."
        elif config.scenario == SimulationScenario.PARTIAL_RECOVERY:
            status = OutcomeStatus.PARTIALLY_RECOVERED
            recovered_amount = payment.amount * Decimal("0.5")
        elif config.scenario == SimulationScenario.PENDING:
            status = OutcomeStatus.PENDING
            recovered_amount = Decimal("0.00")
        else:  # CONTEXT_AWARE
            action_type = execution.action.action_type
            failure_code = payment.failure_code

            if action_type == ActionType.STOP_RECOVERY:
                status = OutcomeStatus.NOT_RECOVERED
                recovered_amount = Decimal("0.00")
                failure_reason = "Recovery stopped by explicit recommendation/policy."

            elif action_type == ActionType.ESCALATE_TO_MERCHANT:
                status = OutcomeStatus.NOT_RECOVERED
                recovered_amount = Decimal("0.00")
                failure_reason = "Case escalated to merchant for manual handling."

            elif action_type in (ActionType.SEND_PAYMENT_LINK, ActionType.SEND_PAYMENT_REMINDER):
                if failure_code == FailureCode.AUTHENTICATION_FAILURE and payment.amount > Decimal("50000.00"):
                    status = OutcomeStatus.NOT_RECOVERED
                    recovered_amount = Decimal("0.00")
                    failure_reason = "Customer authentication challenge failed or abandoned on high-value payment."
                else:
                    status = OutcomeStatus.RECOVERED
                    recovered_amount = payment.amount


            elif action_type in (ActionType.RETRY_IMMEDIATE, ActionType.RETRY_AFTER_DELAY):
                if failure_code in (FailureCode.BANK_TIMEOUT, FailureCode.NETWORK_FAILURE, FailureCode.TEMPORARY_DEGRADATION):
                    status = OutcomeStatus.RECOVERED
                    recovered_amount = payment.amount
                elif failure_code == FailureCode.INSUFFICIENT_FUNDS:
                    # Deterministic behavior: initial retry fails, subsequent attempt/link succeeds
                    if "1" in idempotency_key.split("_")[-1] or payment.attempt_number == 1:
                        status = OutcomeStatus.NOT_RECOVERED
                        recovered_amount = Decimal("0.00")
                        failure_reason = "Insufficient account balance on first retry."
                    else:
                        status = OutcomeStatus.RECOVERED
                        recovered_amount = payment.amount
                elif failure_code == FailureCode.CARD_DECLINED:
                    status = OutcomeStatus.NOT_RECOVERED
                    recovered_amount = Decimal("0.00")
                    failure_reason = "Card decline persisted on retry attempt."
                else:
                    if payment.amount <= Decimal("10000.00"):
                        status = OutcomeStatus.RECOVERED
                        recovered_amount = payment.amount
                    else:
                        status = OutcomeStatus.NOT_RECOVERED
                        recovered_amount = Decimal("0.00")
                        failure_reason = "Retry failed for high value payment failure."

            else:
                status = OutcomeStatus.NOT_RECOVERED
                recovered_amount = Decimal("0.00")
                failure_reason = f"Unhandled action type {action_type}."

        # Apply explicit overrides if provided
        if config.force_status:
            status = OutcomeStatus(config.force_status)
        if config.force_recovered_amount is not None:
            recovered_amount = config.force_recovered_amount
        if config.force_failure_reason is not None:
            failure_reason = config.force_failure_reason

        # 5. Update execution state
        if status == OutcomeStatus.RECOVERED or status == OutcomeStatus.PARTIALLY_RECOVERED:
            execution.status = ExecutionStatus.COMPLETED
            execution.completed_at = datetime.now()
            execution.provider_reference = f"sim_tx_{uuid.uuid4().hex[:10]}"
        elif status == OutcomeStatus.PENDING:
            execution.status = ExecutionStatus.DISPATCHED
        else:
            execution.status = ExecutionStatus.FAILED
            execution.completed_at = datetime.now()
            execution.error_message = failure_reason

        # 6. Construct RecoveryOutcome
        outcome = RecoveryOutcome(
            outcome_id=f"out_{uuid.uuid4().hex[:12]}",
            case_id=execution.case_id,
            execution_id=execution.execution_id,
            status=status,
            recovered_amount=recovered_amount,
            failure_reason=failure_reason,
            verified_at=datetime.now(),
        )

        # 7. Store in execution registry for idempotency
        self._execution_registry[idempotency_key] = outcome

        return outcome

    def get_registered_outcome(self, idempotency_key: str) -> Optional[RecoveryOutcome]:
        """Returns registered outcome for an idempotency key if present."""
        return self._execution_registry.get(idempotency_key)

    def clear_registry(self) -> None:
        """Clears in-memory execution registry (useful between test runs)."""
        self._execution_registry.clear()
